In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('student_pass_fail.csv')

In [3]:
df.shape

(100, 2)

In [4]:
df.head()

Study_Hours  Pass
0            6     1
1            3     0
2           10     1
3            7     1
4            4     0

In [5]:
X = df[['Study_Hours']].values
y = df['Pass'].values

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

In [11]:
model = Sequential()
model.add(Dense(6, input_dim=1, activation='relu'))  
model.add(Dense(6, input_dim=1, activation='relu'))
model.add(Dense(4, input_dim=1, activation='relu'))      
model.add(Dense(1, input_dim=1, activation='sigmoid')) 

c:\Users\shris\miniconda3\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
model.compile(optimizer='Adam',loss='binary_crossentropy')

In [13]:
model.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 0.6978
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6966 
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6953
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6943 
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.6933
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.6927
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6921
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.6917
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6915 
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6913
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.6912
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6911
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6908
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6907
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6905
Epoch 16/100
3/3 ━━━

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 6)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 6)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 4)              │            28 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 263 (1.03 KB)

 Trainable params: 87 (348.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 176 (708.00 B)

In [15]:
model.layers[0].get_weights()

[array([[0.7585522 , 0.03854102, 0.21816716, 0.2539323 , 0.6823818 ,
         0.9691744 ]], dtype=float32),
 array([-0.00285704, -0.04162017, -0.05675717,  0.14118652,  0.2622084 ,
        -0.00486224], dtype=float32)]

In [16]:
y_log = model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step


In [17]:
y_log

array([[0.41783324],
       [0.54882455],
       [0.54882455],
       [0.41783324],
       [0.41783324],
       [0.54882455],
       [0.45839003],
       [0.54882455],
       [0.54882455],
       [0.5346101 ],
       [0.41783324],
       [0.54882455],
       [0.45839003],
       [0.54882455],
       [0.41783324],
       [0.41783324],
       [0.41783324],
       [0.45839003],
       [0.41783324],
       [0.54882455]], dtype=float32)

In [18]:
y_pred = np.where(y_log>0.5,1,0)

In [19]:
y_pred

array([[0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1]])

In [20]:
y_test

array([0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

In [21]:
from sklearn.metrics import accuracy_score

In [23]:
accuracy_score(y_test,y_pred)

1.0